final List<Map<String, String>> funktionen = [
  {
    'anzeigename': 'Teamleiter',
    'fachbereich': 'Softwareentwicklung',
    'abteilung': 'IT',
    'telefon': '+41 31 123 4567',
  },
  {
    'anzeigename': 'Projektmanager',
    'fachbereich': 'Marketing',
    'abteilung': 'Werbung',
    'telefon': '+41 31 234 5678',
  },
  {
    'anzeigename': 'Entwickler',
    'fachbereich': 'App-Entwicklung',
    'abteilung': 'IT',
    'telefon': '+41 31 345 6789',
  },
  {
    'anzeigename': 'HR-Spezialist',
    'fachbereich': 'Personalwesen',
    'abteilung': 'HR',
    'telefon': '+41 31 456 7890',
  },
  {
    'anzeigename': 'Finanzanalyst',
    'fachbereich': 'Finanzen',
    'abteilung': 'Buchhaltung',
    'telefon': '+41 31 567 8901',
  },
  {
    'anzeigename': 'Data Scientist',
    'fachbereich': 'Datenanalyse',
    'abteilung': 'IT',
    'telefon': '+41 31 678 9012',
  },
  {
    'anzeigename': 'Vertriebler',
    'fachbereich': 'Sales',
    'abteilung': 'Vertrieb',
    'telefon': '+41 31 789 0123',
  },
  {
    'anzeigename': 'UX Designer',
    'fachbereich': 'Design',
    'abteilung': 'Produktentwicklung',
    'telefon': '+41 31 890 1234',
  },
  {
    'anzeigename': 'SEO Spezialist',
    'fachbereich': 'Online Marketing',
    'abteilung': 'Marketing',
    'telefon': '+41 31 901 2345',
  },
  {
    'anzeigename': 'IT-Support',
    'fachbereich': 'IT-Infrastruktur',
    'abteilung': 'IT',
    'telefon': '+41 31 012 3456',
  },
  {
    'anzeigename': 'Qualitätsmanager',
    'fachbereich': 'Qualitätssicherung',
    'abteilung': 'Produktion',
    'telefon': '+41 31 234 6789',
  },
  {
    'anzeigename': 'Logistiker',
    'fachbereich': 'Transport & Logistik',
    'abteilung': 'Logistik',
    'telefon': '+41 31 345 6789',
  },
  {
    'anzeigename': 'Einkäufer',
    'fachbereich': 'Beschaffung',
    'abteilung': 'Einkauf',
    'telefon': '+41 31 456 7890',
  },
  {
    'anzeigename': 'Produktmanager',
    'fachbereich': 'Produktentwicklung',
    'abteilung': 'Marketing',
    'telefon': '+41 31 567 8901',
  },
  {
    'anzeigename': 'Werkstattleiter',
    'fachbereich': 'Technik',
    'abteilung': 'Produktion',
    'telefon': '+41 31 678 9012',
  },
  {
    'anzeigename': 'Betriebswirt',
    'fachbereich': 'Controlling',
    'abteilung': 'Finanzen',
    'telefon': '+41 31 789 0123',
  },
  {
    'anzeigename': 'Rechtsanwalt',
    'fachbereich': 'Recht',
    'abteilung': 'Rechtsabteilung',
    'telefon': '+41 31 890 1234',
  },
  {
    'anzeigename': 'Kundendienstmitarbeiter',
    'fachbereich': 'Support',
    'abteilung': 'Kundendienst',
    'telefon': '+41 31 901 2345',
  },
  {
    'anzeigename': 'Geschäftsführer',
    'fachbereich': 'Management',
    'abteilung': 'Geschäftsleitung',
    'telefon': '+41 31 012 3456',
  },
];
