final List<Map<String, String>> personen = [
  {
    'name': 'Müller',
    'vorname': 'Hans',
    'funktion': 'Teamleiter',
    'fachbereich': 'Softwareentwicklung',
    'abteilung': 'IT',
    'telefon': '+49 123 456789',
    'email': 'hans.mueller@example.com',
  },
  {
    'name': 'Schmidt',
    'vorname': 'Anna',
    'funktion': 'Projektmanagerin',
    'fachbereich': 'Marketing',
    'abteilung': 'Werbung',
    'telefon': '+49 987 654321',
    'email': 'anna.schmidt@example.com',
  },
  {
    'name': 'Weber',
    'vorname': 'Michael',
    'funktion': 'Entwickler',
    'fachbereich': 'App-Entwicklung',
    'abteilung': 'IT',
    'telefon': '+49 234 567890',
    'email': 'michael.weber@example.com',
  },
  {
    'name': 'Koch',
    'vorname': 'Laura',
    'funktion': 'HR-Spezialistin',
    'fachbereich': 'Personalwesen',
    'abteilung': 'HR',
    'telefon': '+49 345 678901',
    'email': 'laura.koch@example.com',
  },
  {
    'name': 'Hofmann',
    'vorname': 'Thomas',
    'funktion': 'Finanzanalyst',
    'fachbereich': 'Finanzen',
    'abteilung': 'Buchhaltung',
    'telefon': '+49 456 789012',
    'email': 'thomas.hofmann@example.com',
  },
];
